### ISSUE TITLE
升到2级可能无法触发连击法杖效果的bug

### ISSUE THREAD

**Issue by sxysxy** [SpiritedAwayCN/Mota-Dongchuangshifa-H5Replica#1]
触发方式（前提条件：拿的连击法杖，别的我没试过。第一次到达27层拿黄宝石升2级）：

<img width="972" alt="image" src="https://github.com/SpiritedAwayCN/Mota-Dongchuangshifa-H5Replica/assets/16396193/a05e9d0b-f715-49d6-8b85-481c507fc08f">

拿到黄宝石之后，连击变为2，此时还一切正常：

<img width="955" alt="image" src="https://github.com/SpiritedAwayCN/Mota-Dongchuangshifa-H5Replica/assets/16396193/abd05f8f-7428-458a-a9cf-746bb8d78bc5">

然后读档读到拿到这个黄宝石之前，再到这里拿黄宝石：

<img width="982" alt="image" src="https://github.com/SpiritedAwayCN/Mota-Dongchuangshifa-H5Replica/assets/16396193/3801beb2-983a-4c1b-abf6-a560f76a28e9">

此时可以发现，连击数为1，没有升级到2。

由于前期黄宝石稀少，这个bug会直接导致卡关。

后来发现关闭浏览器页面，重新打开游戏，读档到拿到这个黄宝石之前，再拿黄宝石，连击能正常到2。总之就是读档后重新升级可能无法触发法杖升级效果。

**Comment by SpiritedAwayCN** [comment]
感谢反馈！Github版本已修复，H5平台可能需要一点延迟才能更新。
如果你在H5平台游玩，可以使用如下方法暂时恢复：
读档后拿到黄宝石升级前，按F12打开浏览器控制台，选择‘console’，并输入:
```js
core.refreshComboWand();
```
此操作不会导致录像变红。
